# roles/nfs/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Ensure RPC bind is running
  service:
    name: rpcbind
    state: started
    enabled: true
  tags: install

- name: Provision NFS directories
  file:
    path: "{{ item.mountpoint }}"
    state: directory
    owner: "{{ item.uid }}"
    group: "{{ item.gid }}"
    mode: "{{ openio_nfs_mountpoint_mode }}"
  with_items:
    - "{{ openio_nfs_exports }}"
  tags: configure

- name: Generate exports
  template:
    src: "exports.j2"
    dest: "/etc/exports"
    owner: root
    group: root
    mode: 0644
  register: _nfs_conf
  tags: configure

- name: Restart nfs
  service:
    name: "{{ openio_nfs_daemon }}"
    state: restarted
    enabled: true
  when:
    - openio_nfs_systemd_managed
    - _nfs_conf.changed
    - not openio_nfs_provision_only
  tags: configure
...
